name: Web

on:
  workflow_call:
  pull_request:
    paths:
      - "apps/web/**"

jobs:
  build-and-test-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web

    env:
      VITE_API_URL: ${{ secrets.VITE_API_URL }}

    steps:
      - name: ğŸ§© Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ§© Setup Environment
        uses: ./.github/actions/setup-env

      - name: ğŸ“¦ Install dependencies
        run: npm ci

      - name: ğŸŒ Build Web
        run: |
          npm run build --if-present

      - name: ğŸ§ª Test Web
        run: npm test
